/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface RevoDropdown {
        /**
          * Where to append element
         */
        "appendTo": 'body'|'current';
        /**
          * Should dropdown autoclose on changeValue
         */
        "autoClose": boolean;
        /**
          * Define object mapping for id/value
         */
        "dataId": string;
        /**
          * Define object mapping for labels
         */
        "dataLabel": string;
        /**
          * Change value
         */
        "doChange": (val: any, originalEvent?: MouseEvent) => Promise<void>;
        /**
          * Close dropdown
         */
        "doClose": () => Promise<void>;
        /**
          * Open dropdown
         */
        "doOpen": () => Promise<void>;
        /**
          * Filter criteria
         */
        "filter": 'contains'|'start';
        "hasFilter": boolean;
        /**
          * Placeholder text
         */
        "placeholder": string;
        /**
          * Define object mapping for id/value
         */
        "source": any[];
        /**
          * Selected value
         */
        "value": any;
    }
    interface RevoList {
        /**
          * Define object mapping for labels
         */
        "dataLabel": string;
        "isFocused": boolean;
        "refresh": (source: any[]) => Promise<void>;
        /**
          * Define object mapping for id/value
         */
        "sourceItems": any[];
    }
    interface RevoListFilter {
        /**
          * Define object mapping for labels
         */
        "dataLabel": string;
        "doFilter": (val?: string) => Promise<void>;
        "filter": 'contains'|'start';
        "filterByValue": string;
        "hasFilter": boolean;
        "isFocused": boolean;
        /**
          * Define object mapping for id/value
         */
        "source": any[];
    }
}
declare global {
    interface HTMLRevoDropdownElement extends Components.RevoDropdown, HTMLStencilElement {
    }
    var HTMLRevoDropdownElement: {
        prototype: HTMLRevoDropdownElement;
        new (): HTMLRevoDropdownElement;
    };
    interface HTMLRevoListElement extends Components.RevoList, HTMLStencilElement {
    }
    var HTMLRevoListElement: {
        prototype: HTMLRevoListElement;
        new (): HTMLRevoListElement;
    };
    interface HTMLRevoListFilterElement extends Components.RevoListFilter, HTMLStencilElement {
    }
    var HTMLRevoListFilterElement: {
        prototype: HTMLRevoListFilterElement;
        new (): HTMLRevoListFilterElement;
    };
    interface HTMLElementTagNameMap {
        "revo-dropdown": HTMLRevoDropdownElement;
        "revo-list": HTMLRevoListElement;
        "revo-list-filter": HTMLRevoListFilterElement;
    }
}
declare namespace LocalJSX {
    interface RevoDropdown {
        /**
          * Where to append element
         */
        "appendTo"?: 'body'|'current';
        /**
          * Should dropdown autoclose on changeValue
         */
        "autoClose"?: boolean;
        /**
          * Define object mapping for id/value
         */
        "dataId"?: string;
        /**
          * Define object mapping for labels
         */
        "dataLabel"?: string;
        /**
          * Filter criteria
         */
        "filter"?: 'contains'|'start';
        "hasFilter"?: boolean;
        /**
          * When value changed
         */
        "onChangeValue"?: (event: CustomEvent<{val: any, originalEvent?: MouseEvent}>) => void;
        /**
          * Before element close, can be prevented
         */
        "onClose"?: (event: CustomEvent<any>) => void;
        /**
          * Before element open, can be prevented
         */
        "onOpen"?: (event: CustomEvent<any>) => void;
        /**
          * Placeholder text
         */
        "placeholder"?: string;
        /**
          * Define object mapping for id/value
         */
        "source"?: any[];
        /**
          * Selected value
         */
        "value"?: any;
    }
    interface RevoList {
        /**
          * Define object mapping for labels
         */
        "dataLabel"?: string;
        "isFocused"?: boolean;
        "onDoChange"?: (event: CustomEvent<{ item: any, e: any }>) => void;
        /**
          * Define object mapping for id/value
         */
        "sourceItems"?: any[];
    }
    interface RevoListFilter {
        /**
          * Define object mapping for labels
         */
        "dataLabel"?: string;
        "filter"?: 'contains'|'start';
        "filterByValue"?: string;
        "hasFilter"?: boolean;
        "isFocused"?: boolean;
        "onDoChange"?: (event: CustomEvent<{ item: any, e: any }>) => void;
        "onFilterChange"?: (event: CustomEvent<string|undefined>) => void;
        /**
          * Define object mapping for id/value
         */
        "source"?: any[];
    }
    interface IntrinsicElements {
        "revo-dropdown": RevoDropdown;
        "revo-list": RevoList;
        "revo-list-filter": RevoListFilter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "revo-dropdown": LocalJSX.RevoDropdown & JSXBase.HTMLAttributes<HTMLRevoDropdownElement>;
            "revo-list": LocalJSX.RevoList & JSXBase.HTMLAttributes<HTMLRevoListElement>;
            "revo-list-filter": LocalJSX.RevoListFilter & JSXBase.HTMLAttributes<HTMLRevoListFilterElement>;
        }
    }
}
