/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DropdownTemplate } from "./components/dropdown/revo-dropdown";
export { DropdownTemplate } from "./components/dropdown/revo-dropdown";
export namespace Components {
    interface RevoDropdown {
        /**
          * Animate dropdown open transition
          * @default true
         */
        "animation": boolean;
        /**
          * Where to append element
          * @default 'body'
         */
        "appendTo": 'body' | 'current' | string;
        /**
          * Should dropdown autoclose on changeValue
          * @default true
         */
        "autoClose": boolean;
        /**
          * @default false
         */
        "autoFocus": boolean;
        /**
          * @default false
         */
        "autocomplete": boolean;
        /**
          * Filter value
         */
        "currentFilter": any;
        /**
          * Define object mapping for id/value
         */
        "dataId": string;
        /**
          * Define object mapping for labels
         */
        "dataLabel": string;
        /**
          * Change value
         */
        "doChange": (val: any, originalEvent?: globalThis.Event) => Promise<void>;
        /**
          * Close dropdown
         */
        "doClose": (isDisconnected?: boolean) => Promise<void>;
        /**
          * Open dropdown
         */
        "doOpen": () => Promise<void>;
        /**
          * Filter criteria
         */
        "filter": 'contains' | 'start';
        /**
          * @default true
         */
        "hasFilter": boolean;
        "maxHeight": number;
        /**
          * Placeholder text
          * @default 'Select'
         */
        "placeholder": string;
        /**
          * Define a vnode template for the selected value. The option `template` remains list-only for backward compatibility.
          * @example <revo-dropdown selectedTemplate={(createElement, item) => createElement('span', null, item.label)} />
         */
        "selectedTemplate"?: DropdownTemplate;
        /**
          * Define object mapping for id/value
          * @default []
         */
        "source": any[];
        /**
          * Define your own vnode template
          * @example <revo-dropdown template={(createElement, item) => createElement('span', null, item.label)} />
         */
        "template"?: DropdownTemplate;
        /**
          * Selected value
         */
        "value": any;
    }
    interface RevoList {
        /**
          * @default false
         */
        "isFocused": boolean;
        "moveSelection": (step: number) => Promise<void>;
        "refresh": (source: any[]) => Promise<void>;
        "selectCurrent": (e: globalThis.Event) => Promise<void>;
        /**
          * Selected Value Index
          * @default 0
         */
        "selectedIndex": number;
        /**
          * Define object mapping for id/value
          * @default []
         */
        "sourceItems": any[];
        "template": (item: any) => unknown;
    }
}
export interface RevoDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRevoDropdownElement;
}
export interface RevoListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRevoListElement;
}
declare global {
    interface HTMLRevoDropdownElementEventMap {
        "changed": { val: any; originalEvent?: globalThis.Event };
        "close": any;
        "open": any;
    }
    interface HTMLRevoDropdownElement extends Components.RevoDropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRevoDropdownElementEventMap>(type: K, listener: (this: HTMLRevoDropdownElement, ev: RevoDropdownCustomEvent<HTMLRevoDropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRevoDropdownElementEventMap>(type: K, listener: (this: HTMLRevoDropdownElement, ev: RevoDropdownCustomEvent<HTMLRevoDropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRevoDropdownElement: {
        prototype: HTMLRevoDropdownElement;
        new (): HTMLRevoDropdownElement;
    };
    interface HTMLRevoListElementEventMap {
        "changed": { item: any; e: globalThis.Event };
    }
    interface HTMLRevoListElement extends Components.RevoList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRevoListElementEventMap>(type: K, listener: (this: HTMLRevoListElement, ev: RevoListCustomEvent<HTMLRevoListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRevoListElementEventMap>(type: K, listener: (this: HTMLRevoListElement, ev: RevoListCustomEvent<HTMLRevoListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRevoListElement: {
        prototype: HTMLRevoListElement;
        new (): HTMLRevoListElement;
    };
    interface HTMLElementTagNameMap {
        "revo-dropdown": HTMLRevoDropdownElement;
        "revo-list": HTMLRevoListElement;
    }
}
declare namespace LocalJSX {
    interface RevoDropdown {
        /**
          * Animate dropdown open transition
          * @default true
         */
        "animation"?: boolean;
        /**
          * Where to append element
          * @default 'body'
         */
        "appendTo"?: 'body' | 'current' | string;
        /**
          * Should dropdown autoclose on changeValue
          * @default true
         */
        "autoClose"?: boolean;
        /**
          * @default false
         */
        "autoFocus"?: boolean;
        /**
          * @default false
         */
        "autocomplete"?: boolean;
        /**
          * Filter value
         */
        "currentFilter"?: any;
        /**
          * Define object mapping for id/value
         */
        "dataId"?: string;
        /**
          * Define object mapping for labels
         */
        "dataLabel"?: string;
        /**
          * Filter criteria
         */
        "filter"?: 'contains' | 'start';
        /**
          * @default true
         */
        "hasFilter"?: boolean;
        "maxHeight"?: number;
        /**
          * When value changed
         */
        "onChanged"?: (event: RevoDropdownCustomEvent<{ val: any; originalEvent?: globalThis.Event }>) => void;
        /**
          * Before element close, can be prevented
         */
        "onClose"?: (event: RevoDropdownCustomEvent<any>) => void;
        /**
          * Before element open, can be prevented
         */
        "onOpen"?: (event: RevoDropdownCustomEvent<any>) => void;
        /**
          * Placeholder text
          * @default 'Select'
         */
        "placeholder"?: string;
        /**
          * Define a vnode template for the selected value. The option `template` remains list-only for backward compatibility.
          * @example <revo-dropdown selectedTemplate={(createElement, item) => createElement('span', null, item.label)} />
         */
        "selectedTemplate"?: DropdownTemplate;
        /**
          * Define object mapping for id/value
          * @default []
         */
        "source"?: any[];
        /**
          * Define your own vnode template
          * @example <revo-dropdown template={(createElement, item) => createElement('span', null, item.label)} />
         */
        "template"?: DropdownTemplate;
        /**
          * Selected value
         */
        "value"?: any;
    }
    interface RevoList {
        /**
          * @default false
         */
        "isFocused"?: boolean;
        "onChanged"?: (event: RevoListCustomEvent<{ item: any; e: globalThis.Event }>) => void;
        /**
          * Selected Value Index
          * @default 0
         */
        "selectedIndex"?: number;
        /**
          * Define object mapping for id/value
          * @default []
         */
        "sourceItems"?: any[];
        "template": (item: any) => unknown;
    }

    interface RevoDropdownAttributes {
        "dataLabel": string;
        "value": string;
        "currentFilter": string;
        "dataId": string;
        "autoClose": boolean;
        "placeholder": string;
        "appendTo": 'body' | 'current' | string;
        "filter": 'contains' | 'start';
        "maxHeight": number;
        "hasFilter": boolean;
        "autocomplete": boolean;
        "animation": boolean;
        "autoFocus": boolean;
    }
    interface RevoListAttributes {
        "isFocused": boolean;
        "selectedIndex": number;
    }

    interface IntrinsicElements {
        "revo-dropdown": Omit<RevoDropdown, keyof RevoDropdownAttributes> & { [K in keyof RevoDropdown & keyof RevoDropdownAttributes]?: RevoDropdown[K] } & { [K in keyof RevoDropdown & keyof RevoDropdownAttributes as `attr:${K}`]?: RevoDropdownAttributes[K] } & { [K in keyof RevoDropdown & keyof RevoDropdownAttributes as `prop:${K}`]?: RevoDropdown[K] };
        "revo-list": Omit<RevoList, keyof RevoListAttributes> & { [K in keyof RevoList & keyof RevoListAttributes]?: RevoList[K] } & { [K in keyof RevoList & keyof RevoListAttributes as `attr:${K}`]?: RevoListAttributes[K] } & { [K in keyof RevoList & keyof RevoListAttributes as `prop:${K}`]?: RevoList[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "revo-dropdown": LocalJSX.IntrinsicElements["revo-dropdown"] & JSXBase.HTMLAttributes<HTMLRevoDropdownElement>;
            "revo-list": LocalJSX.IntrinsicElements["revo-list"] & JSXBase.HTMLAttributes<HTMLRevoListElement>;
        }
    }
}
